model:
  name: 'mlfn'
  pretrained: True

data:
  type: 'image'
  sources: ['bigtosmall']
  targets: ['bigtosmall']
  height: 224
  width: 224
  transforms: ['random_flip', 'random_crop']
  save_dir: 'log/bigtosmall'

cuhk03:
  classic_split: True

loss:
  name: 'triplet'
  softmax:
    label_smooth: True
  triplet:
    weight_t: 0.5
    weight_x: 0.5

train:
  optim: 'amsgrad'
  lr: 0.0003
  max_epoch: 500
  batch_size: 32
  fixbase_epoch: 0
  open_layers: []
  lr_scheduler: 'single_step'
  stepsize: [20]


test:
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 2
  rerank: False
  visrank: False
